version: '3.4'
services:
  mongo:
    image: mongo:4.4
    volumes:
      - dbdata:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # uncomment the following line to pull the image from docker hub
    # image: index.docker.io/catarak/p5.js-web-editor:latest
    env_file:
      - "$PWD/.env"
    # Uncomment following lines to run prod. app locally using docker.
    environment:
      - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - mongo
volumes:
  dbdata:
